version: '3'

services:
  gunicorn:
    build: .
    image: gunicorn:20.1.0
    container_name: movie_collection_gunicorn
    volumes:
      - .:/usr/src/app/
      - gunicorn:/var/run/gunicorn
    restart: always
  nginx:
    image: nginx:1.17.7
    container_name: movie_collection_nginx
    depends_on:
      - gunicorn
    ports:
      - "7010:80"
    volumes:
      - ./gunicorn.conf:/etc/nginx/conf.d/default.conf
      - gunicorn:/var/run/gunicorn
    restart: always
volumes:
  gunicorn:
    driver: local
