# Generated by Django 4.0.2 on 2022-02-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
