# Generated by Django 4.0.2 on 2022-02-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collection_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='creator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
