# Generated by Django 4.1 on 2023-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_rename_creators_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='creator',
        ),
        migrations.AddField(
            model_name='collection',
            name='creator',
            field=models.ManyToManyField(blank=True, to='collection.creator'),
        ),
    ]
