# Generated by Django 4.0.2 on 2022-03-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collection_creator_collection_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='creator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
