# Generated by Django 4.0.2 on 2022-03-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_collection_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='add_by',
            field=models.CharField(default='crashrt', max_length=100),
            preserve_default=False,
        ),
    ]
